[[zig]]
arch = "aarch64"
git-tree-sha1 = "21dd219347e7ae9e0a5a53d0b9ced79b49e40338"
os = "macos"

    [[zig.download]]
    sha256 = "be8fb7557a45a6d7b34c54db91e54918b4e018d15bfd05710333861ac9a78e61"
    url = "https://github.com/JuliaBinaryWrappers/zig_jll.jl/releases/download/zig-v0.11.0+0/zig.v0.11.0.aarch64-apple-darwin.tar.gz"
[[zig]]
arch = "aarch64"
git-tree-sha1 = "4a7122f4f409d001f5befd0e6c34b5d360eb39ae"
libc = "glibc"
os = "linux"

    [[zig.download]]
    sha256 = "e0a7a428e815c8b51deb96c529fc11e50ad125cd39acbf13ffcc34efbfd6e3dd"
    url = "https://github.com/JuliaBinaryWrappers/zig_jll.jl/releases/download/zig-v0.11.0+0/zig.v0.11.0.aarch64-linux-gnu.tar.gz"
[[zig]]
arch = "i686"
git-tree-sha1 = "cf8ea4c486beb8562356ccaa580b439a17a7d069"
libc = "glibc"
os = "linux"

    [[zig.download]]
    sha256 = "6048c3a0d02724572caace45d0b8a1df03808cae1846a8a71b8e0c3874bd515f"
    url = "https://github.com/JuliaBinaryWrappers/zig_jll.jl/releases/download/zig-v0.11.0+0/zig.v0.11.0.i686-linux-gnu.tar.gz"
[[zig]]
arch = "i686"
git-tree-sha1 = "a0ba3eea809bcab7243e020e9444da7fae0cb6ac"
os = "windows"

    [[zig.download]]
    sha256 = "c571d2d9392b962f1e2ee034db34e90f876dc9572b004b85c2ecdda79b1728b4"
    url = "https://github.com/JuliaBinaryWrappers/zig_jll.jl/releases/download/zig-v0.11.0+0/zig.v0.11.0.i686-w64-mingw32.tar.gz"
[[zig]]
arch = "x86_64"
git-tree-sha1 = "7519b355af43750214fbb4401858441fd1bdfaba"
os = "macos"

    [[zig.download]]
    sha256 = "9980938c824e35e3bda56a0984d9bc4ff1549b3fd3a522612f8bf136d9413bbf"
    url = "https://github.com/JuliaBinaryWrappers/zig_jll.jl/releases/download/zig-v0.11.0+0/zig.v0.11.0.x86_64-apple-darwin.tar.gz"
[[zig]]
arch = "x86_64"
git-tree-sha1 = "8574ea15f3c2681315dc2b68f1dd60452da2afa8"
libc = "glibc"
os = "linux"

    [[zig.download]]
    sha256 = "91c8bed94c3d7791de9ae72dfaa0fe2b8f3ef6fae7d19f167d041111ebe9c73c"
    url = "https://github.com/JuliaBinaryWrappers/zig_jll.jl/releases/download/zig-v0.11.0+0/zig.v0.11.0.x86_64-linux-gnu.tar.gz"
[[zig]]
arch = "x86_64"
git-tree-sha1 = "afa14a0cbee45dd569e63c13abb1de2b9f064b1c"
os = "freebsd"

    [[zig.download]]
    sha256 = "717735807dadeee40a7c153fa80caea9e901bbda869eb934015403bf2c8cc32f"
    url = "https://github.com/JuliaBinaryWrappers/zig_jll.jl/releases/download/zig-v0.11.0+0/zig.v0.11.0.x86_64-unknown-freebsd.tar.gz"
[[zig]]
arch = "x86_64"
git-tree-sha1 = "27b9f55e9c432e24e799adc83d883a706684fe98"
os = "windows"

    [[zig.download]]
    sha256 = "d894393b011050247d91a1e2d974ba712afc68e83ce9292179a0b7363fb3602e"
    url = "https://github.com/JuliaBinaryWrappers/zig_jll.jl/releases/download/zig-v0.11.0+0/zig.v0.11.0.x86_64-w64-mingw32.tar.gz"
