# Autogenerated wrapper script for zig_jll for x86_64-w64-mingw32
export zig

JLLWrappers.@generate_wrapper_header("zig")
JLLWrappers.@declare_executable_product(zig)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        zig,
        "bin\\zig\\zig.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
